# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    pull_request:
        branches: [main]

jobs:
    build:
        timeout-minutes: 5
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18]

        steps:
            # - uses: actions/checkout@v4
            #   with:
            #     fetch-depth: 0
            # - name: sonarQube scancode
            #   uses: sonarsource/sonarqube-scan-action@master
            #   env:
            #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            #       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
            #- uses: sonarsource/sonarqube-quality-gate-action@master
            #  timeout-minutes: 5
            #  env:
            #      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm test
